name: PR Template Selector

on:
  pull_request:
    types: [opened, edited]

jobs:
  select-template:
    runs-on: ubuntu-latest
    steps:
      - name: Select PR template
        run: |
          if [[ "$GITHUB_EVENT_LABEL" == "feature" ]]; then
            echo "Feature Template Content" > pr_template.md
          elif [[ "$GITHUB_EVENT_LABEL" == "bugfix" ]]; then
            echo "Bugfix Template Content" > pr_template.md
          fi
          gh pr edit ${{ github.event.pull_request.number }} --body "$(cat pr_template.md)"
